-- Truncate existing product data to start fresh (only if safe, otherwise just insert)
-- Using ON CONFLICT logic or explicit IDs for safety
-- Assuming 'products' table exists

-- Clear existing products to ensure clean slate with new image links
DELETE FROM products;

-- Insert 7 new products with the provided Google Drive image links
-- Image Link Conversion:
-- https://drive.google.com/file/d/ID/view -> https://drive.google.com/uc?export=view&id=ID

INSERT INTO products (
    id,
    name,
    tagline,
    category,
    price,
    originalprice,
    image,
    description,
    features,
    colors,
    sizes,
    instock,
    rating,
    stockquantity,
    gender,
    isdeleted
) VALUES 
(
    'p_v2_001',
    'AeroStride Pro',
    'Performance Redefined',
    'Shoes',
    12999,
    15999,
    'https://drive.google.com/uc?export=view&id=1tEuedCwZYRWL-aYCOXY46bXCBcnyVuU-',
    'Engineered for elite runners, the AeroStride Pro combines lightweight materials with responsive cushioning.',
    ARRAY['Carbon Fiber Plate', 'Breathable Mesh', 'High-Traction Sole'],
    ARRAY['Black', 'Volt Green'],
    ARRAY['UK 7', 'UK 8', 'UK 9', 'UK 10'],
    true,
    4.8,
    45,
    'Men',
    false
),
(
    'p_v2_002',
    'Urban Glide',
    'City Comfort',
    'Shoes',
    8499,
    10999,
    'https://drive.google.com/uc?export=view&id=1pc6UNVFR889igs7LbnQml_DpWpVd5AP2',
    'The perfect companion for urban exploration, featuring all-day comfort and sleek design.',
    ARRAY['Memory Foam Insole', 'Slip-Resistant', 'Easy-Clean Upper'],
    ARRAY['Grey', 'Navy'],
    ARRAY['UK 6', 'UK 7', 'UK 8', 'UK 9'],
    true,
    4.6,
    60,
    'Unisex',
    false
),
(
    'p_v2_003',
    'Midnight Force',
    'Stealth & Power',
    'Shoes',
    14499,
    18999,
    'https://drive.google.com/uc?export=view&id=1JAkZKl652biLyzUdO5X05Y4s7a1AsqPU',
    'Dominate the court or the street with the Midnight Force. Unmatched stability and style.',
    ARRAY['Ankle Support', 'Durable Rubber Outsole', 'Reflective Details'],
    ARRAY['Black/Red', 'Triple Black'],
    ARRAY['UK 8', 'UK 9', 'UK 10', 'UK 11'],
    true,
    4.9,
    30,
    'Men',
    false
),
(
    'p_v2_004',
    'Velocity Elite',
    'Speed Unleashed',
    'Shoes',
    11999,
    14999,
    'https://drive.google.com/uc?export=view&id=19UKGRbcIZHffq1xs56MekmVpgF90H2kr',
    'Built for speed training and race day. Minimalist design for maximum output.',
    ARRAY['Ultra-Lightweight', 'Responsive Foam', 'Seamless Knit'],
    ARRAY['White/Blue', 'Orange'],
    ARRAY['UK 7', 'UK 8', 'UK 9'],
    true,
    4.7,
    25,
    'Unisex',
    false
),
(
    'p_v2_005',
    'Stealth Commuter',
    'Organized Efficiency',
    'Bags',
    5999,
    7999,
    'https://drive.google.com/uc?export=view&id=1fm0yzmL6IQktGcvEZ34X3hF3YaVqcYoC',
    'A sleek backpack designed for the modern professional. Water-resistant and packed with smart storage.',
    ARRAY['Water Resistant', 'Laptop Compartment', 'Hidden Pockets'],
    ARRAY['Black', 'Charcoal'],
    ARRAY['One Size'],
    true,
    4.8,
    100,
    'Unisex',
    false
),
(
    'p_v2_006',
    'Modular Tote',
    'Versatile Utility',
    'Bags',
    4499,
    5999,
    'https://drive.google.com/uc?export=view&id=1P2Rdo8iTmbVCLJ7bKG8SRiYdjoiEl5TZ',
    'From gym to office, this tote adapts to your needs. Durable and stylish.',
    ARRAY['Expandable Volume', 'Detachable Strap', 'Reinforced Base'],
    ARRAY['Olive', 'Black'],
    ARRAY['One Size'],
    true,
    4.5,
    80,
    'Women',
    false
),
(
    'p_v2_007',
    'Tech Sling',
    'Essential Carry',
    'Accessories',
    2999,
    3999,
    'https://drive.google.com/uc?export=view&id=1BB5uMVdb66bRJLUgle-vUkLaKyK1gC-i',
    'Keep your essentials close and secure. Perfect for travel or daily errands.',
    ARRAY['RFID Blocking', 'Quick-Access pocket', 'Adjustable Strap'],
    ARRAY['Black', 'Camo'],
    ARRAY['One Size'],
    true,
    4.6,
    150,
    'Unisex',
    false
);
